[package]
name = "tokenum"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = { version = "0.1.10" }
thiserror = { version = "1.0" }
tiktoken-rs = { version = "0.7.0" }
anyhow = { version = "1.0" }
ignore = { version = "0.4.22" }
termtree = { version = "0.4" }
